# 预备知识

#### Python基础(一些语法糖)

In [5]:
# 列表推导式(支持多层嵌套)
print([m + ' ' + n for m in ['ustc', 'nico'] for n in ['edu', 'com']]) 
# 带if选择的条件赋值
value = '666' if 2 > 1 else '444'
print(value)

# 匿名函数
print([(lambda x: x * x)(i) for i in range(10)])
# 用map函数实现, 需要调用list()函数转换为列表
print(list(map(lambda x: x * x, range(10))))

# zip函数将可迭代对象打包成元组, 通常用于循环
L1 = [1, 2, 3, 4]
L2 = ['a', 'b', 'c', 'd']
print(list(zip(L1, L2)))
# 解压操作zip(*)
print(list(zip(*zip(L1, L2))))
for (x, y) in zip(L1, L2):
    print(x, y)
# enumerate函数在迭代时绑定遍历序号, 通常用于循环
print('enumerate result:')
for index, value in enumerate(L2):
    print(index, value)
# 对两个列表建立字典映射时, 可以用zip函数
print(dict(zip(L1, L2)))

['ustc edu', 'ustc com', 'nico edu', 'nico com']
666
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]
[(1, 2, 3, 4), ('a', 'b', 'c', 'd')]
1 a
2 b
3 c
4 d
enumerate result:
0 a
1 b
2 c
3 d
{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


#### Numpy基础

In [16]:
# numpy数组构造
import numpy as np
print(np.array([1, 2, 3]))
# 生成等差数列
print(np.arange(0, 10, 2)) # 起始值, 终止值, 步长
print(np.linspace(1, 5, 11)) # 起始值, 终止值, 样本个数
# 特殊矩阵
print('全0矩阵')
print(np.zeros((2, 3))) # 全0矩阵
print('单位矩阵')
print(np.eye(3)) # 3*3单位矩阵
print(np.eye(3, k=1)) # 3*3单位矩阵, 偏移主对角线为1
print('对角矩阵')
print(np.diag([1, 2, 3])) # 对角矩阵
print('全10矩阵')
print(np.full((2, 3), 10)) # 全10矩阵
print('随机矩阵')
print(np.random.rand(2, 3)) # 随机矩阵0-1均匀分布
print(np.random.randn(2, 3)) # 随机矩阵标准正态分布
print(np.random.randint(0, 10, (2, 3))) # 随机矩阵整数均匀分布(2, 3)为维度
print(np.random.choice([10, 20, 30], (3, 3), p=[0.4, 0.2, 0.4]))# 以一定概率进行选择
print(np.random.permutation(['ustc', 'nico', 'edu', 'com'])) # 打散原列表

[1 2 3]
[0 2 4 6 8]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
全0矩阵
[[0. 0. 0.]
 [0. 0. 0.]]
单位矩阵
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
对角矩阵
[[1 0 0]
 [0 2 0]
 [0 0 3]]
全10矩阵
[[10 10 10]
 [10 10 10]]
随机矩阵
[[0.13371985 0.89374354 0.77169338]
 [0.98236722 0.73904041 0.30859929]]
[[-1.89460649 -0.25769103  0.1788687 ]
 [-1.18546341 -1.14782278 -1.84632015]]
[[1 7 3]
 [9 9 1]]
[[30 20 10]
 [20 20 20]
 [30 30 20]]
['edu' 'ustc' 'com' 'nico']


In [38]:
# numpy数组变形、合并等操作
# 转置
print(np.zeros((2,4)).T)
# 合并
print(np.r_[np.zeros((2, 3)), np.ones((2, 3))]) # 按行合并
print(np.c_[np.zeros((2, 3)), np.ones((2, 3))]) # 按列合并
print(np.c_[np.array([1,1]), np.zeros((2, 3))]) # 一维二维数组合并, 按列合并
# 维度变换 
print(np.random.randn(6).reshape((3, 2))) # 2*3变为3*2
print(np.random.randn(2,3).reshape(-1)) # reshape(-1)将多维数组变为一维数组, 允许一个维数空缺
# 数组切片
print(np.arange(9).reshape(3, 3))
print(np.arange(9).reshape(3, 3)[1:3, 1:3]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[1:3, :]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[np.ix_([1,2], [True, False, True])]) # 在对应的维度上使用布尔索引, 此时不能使用slice切片

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[-0.24454107  0.52428338]
 [ 0.7650059  -1.07872579]
 [ 0.13288399 -0.72405317]]
[-0.53593531 -0.87311507  0.19633392 -0.43977484 -0.36122564 -0.8701521 ]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[[3 4 5]
 [6 7 8]]
[[3 5]
 [6 8]]


In [55]:
# 常用函数
# where函数指定满足条件和不满足条件的填充值
print(np.where(np.arange(9).reshape(3, 3) > 0, 1, 0))
# 返回索引函数: nonzero, argmax, argmin
# nonzero返回非零元素的索引
print(np.nonzero(np.arange(9)))
# argmax返回最大值的索引
print(np.argmax(np.arange(9)))
# argmin返回最小值的索引
print(np.argmin(np.arange(9)))
# any函数: 当序列至少有一个True或非零元素时返回True
print(np.any(np.arange(2)))
# all函数: 当序列所有元素都为True或非零元素时返回True
print(np.all(np.arange(2)))
print(np.arange(1, 5))
# cumprod函数: 返回给定序列的累积乘法结果
print(np.cumprod(np.arange(1, 5)))
# cumsum函数: 返回给定序列的累积加法结果
print(np.cumsum(np.arange(1, 5)))
# diff函数: 返回给定序列的累积差值, 返回长度比原序列少1
print(np.diff(np.arange(1, 5)))
# 统计函数: sum, mean, std, var, max, min, median, average, quantile(全局函数, 不能通过array.quantile()调用)
print(np.quantile(np.arange(1, 5), 0.5)) # 返回给定序列的分位数, 这里是中位数
# 忽略有缺失值数组
print(np.array([1, 2, np.nan, 3]))
print(np.nansum(np.array([1, 2, np.nan, 3])))
print('协方差、相关系数的计算')
print(np.cov(np.array([1, 3, 5, 9]), np.array([1, 5, 3, -9]))) # 协方差
print(np.corrcoef(np.array([1, 2, 5]), np.array([2, 5, 6]))) # 相关系数
# 二维NUmpy数组的axis参数: axis=0表示列的统计指标; axis=1表示行的统计指标
print(np.arange(9).reshape(3, 3).sum(axis=0))
print(np.arange(9).reshape(3, 3).sum(axis=1))

[[0 1 1]
 [1 1 1]
 [1 1 1]]
(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)
8
0
True
False
[1 2 3 4]
[ 1  2  6 24]
[ 1  3  6 10]
[1 1 1]
2.5
[ 1.  2. nan  3.]
6.0
协方差、相关系数的计算
[[ 11.66666667 -16.66666667]
 [-16.66666667  38.66666667]]
[[1.         0.84615385]
 [0.84615385 1.        ]]
[ 9 12 15]
[ 3 12 21]


In [74]:
# 广播机制处理不同维度数组之间的操作
# 标量和数组的操作, 标量自动把大小扩充为数组大小
print(3 * np.random.rand(2, 3) + 2)
# 二维数组之间的操作, 其中一个维度实1*m或者n*1, 则自动扩充为m*n
print(np.ones((2, 3)) + np.zeros((1, 3)))
# 一维数组与二维数组的操作, 将一维数组视作1*m的二维数组
print(np.arange(3) + np.ones((3, 3)))
# 向量内积的计算
print(np.arange(3).dot(np.arange(2, 5)))
# 向量范数和矩阵范数
print(np.linalg.norm(np.arange(4).reshape(2, 2), 'fro'))
# 矩阵乘法
print(np.arange(4).reshape(2, 2) @ (np.arange(4).reshape(2, 2)))


[[4.35869895 4.31867726 3.80496064]
 [4.38257599 2.24020113 4.26423098]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
11
3.7416573867739413
[[ 2  3]
 [ 6 11]]


# Pandas基础

#### 文件读取和写入

In [11]:
import numpy as np
import pandas as pd
# 文件读取
# header=None表示不把第一行作为列名
df_csv = pd.read_csv('../data/my_csv.csv', parse_dates=['col5']) # parse_dates表示把某列作为日期
print(df_csv)
df_txt = pd.read_table('../data/my_table.txt', index_col=['col1', 'col3']) # 表示把某几列作为索引
print(df_txt)
df_excel = pd.read_excel('../data/my_excel.xlsx', usecols=['col3', 'col4', 'col5'], nrows=3) # 表示读取列的集合, 行数
print(df_excel)
print(pd.read_table('../data/my_table_special_sep.txt'))
print(pd.read_table('../data/my_table_special_sep.txt', sep=' \|\|\|\| ', engine='python')) # 使用sep指定分隔符, engine指定解析器
# 文件写入
df_csv.to_csv('../data/my_csv_saved.csv', index=False) # index=False表示不保存索引
df_excel.to_excel('../data/my_excel_saved.xlsx', index=False)
df_txt.to_csv('../data/my_txt_saved.txt', sep='\t', index=False) # sep指定分隔符, pandas没有to_table函数
# 表格转换
import tabulate
print(df_csv.to_markdown()) # 转换为markdown格式
print(df_csv.to_latex()) # 转换为latex格式

<>:12: SyntaxWarning: invalid escape sequence '\|'
<>:12: SyntaxWarning: invalid escape sequence '\|'
C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_17600\4037761022.py:12: SyntaxWarning: invalid escape sequence '\|'
  print(pd.read_table('../data/my_table_special_sep.txt', sep=' \|\|\|\| ', engine='python')) # 使用sep指定分隔符, engine指定解析器


   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05
3     5    d   3.2   lemon 2020-01-07
          col2             col4
col1 col3                      
2    1.4     a   apple 2020/1/1
3    3.4     b  banana 2020/1/2
6    2.5     c  orange 2020/1/5
5    3.2     d   lemon 2020/1/7
   col3    col4      col5
0   1.4   apple  2020/1/1
1   3.4  banana  2020/1/2
2   2.5  orange  2020/1/5
              col1 |||| col2
0  TS |||| This is an apple.
1    GQ |||| My name is Bob.
2         WT |||| Well done!
3    PT |||| May I help you?
  col1               col2
0   TS  This is an apple.
1   GQ    My name is Bob.
2   WT         Well done!
3   PT    May I help you?
|    |   col1 | col2   |   col3 | col4   | col5                |
|---:|-------:|:-------|-------:|:-------|:--------------------|
|  0 |      2 | a      |    1.4 | apple  | 2020-01-01 00:00:00 |
|  1 |      3 | b      |    3.4 | banana | 2

#### 基本数据结构

In [15]:
import numpy as np
import pandas as pd
# 存储一维的Series由序列值data、索引index、存储类型dtype、序列名字name四部分组成
# Series创建
series = pd.Series(data=[100, 'a', {'dict': 1}], index=pd.Index(['id1', 20, 'third'], name='my_series'), dtype='object', name='my_name')
print(series)
# 通过.获取属性
print(series.values)
print(series.index)
print(series.dtype)
print(series.name)
print('序列长度', series.shape)

# 存储二维的DataFrame由数据data、行索引index、列索引columns、存储类型dtype等组成
# DataFrame创建
dataframe = pd.DataFrame([[1, 'a', 1.2], [2, 'b', 2.2], [3, 'c', 3.2]], index=pd.Index(['row1', 'row2', 'row3'], name='my_rows'), columns=pd.Index(['id', 'name', 'score'], name='my_columns'))
print(dataframe)
# 取出列
print('提取列')
print(dataframe['id'])
print(dataframe[['name', 'score']])
# 取出行
print('提取行')
print(dataframe.loc['row1'])
# 通过.获取属性
print('获取属性')
print(dataframe.values)
print(dataframe.index)
print(dataframe.columns)
print(dataframe.dtypes)
print(dataframe.shape)
# 转置
print('转置dataframe')
print(dataframe.T)


my_series
id1              100
20                 a
third    {'dict': 1}
Name: my_name, dtype: object
[100 'a' {'dict': 1}]
Index(['id1', 20, 'third'], dtype='object', name='my_series')
object
my_name
序列长度 (3,)
my_columns  id name  score
my_rows                   
row1         1    a    1.2
row2         2    b    2.2
row3         3    c    3.2
提取列
my_rows
row1    1
row2    2
row3    3
Name: id, dtype: int64
my_columns name  score
my_rows               
row1          a    1.2
row2          b    2.2
row3          c    3.2
提取行
my_columns
id         1
name       a
score    1.2
Name: row1, dtype: object
获取属性
[[1 'a' 1.2]
 [2 'b' 2.2]
 [3 'c' 3.2]]
Index(['row1', 'row2', 'row3'], dtype='object', name='my_rows')
Index(['id', 'name', 'score'], dtype='object', name='my_columns')
my_columns
id         int64
name      object
score    float64
dtype: object
(3, 3)
转置dataframe
my_rows    row1 row2 row3
my_columns               
id            1    2    3
name          a    b    c
score       1.2  2.2

#### 基本函数

In [23]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/learn_pandas.csv')
print(df.columns)
# 提取前7列
df = df[df.columns[:7]]
print(df.columns)
# 汇总函数
print('汇总函数')
print(df.head(3)) # head函数返回前n行
print(df.tail(4)) # tail函数返回后n行
print(df.info()) # info函数返回信息概况
print(df.describe()) # describe函数返回数值列的汇总统计
# 特征统计函数
print('特征统计函数')
df_test = df[['Height', 'Weight']]
print(df_test.mean()) # mean函数返回均值
print(df_test.max()) # max函数返回最大值
print(df_test.quantile(0.75)) # quantile函数返回分位数
print(df_test.count()) # count函数返回非缺失值元素个数
print(df_test.idxmax()) # idxmax函数返回最大值的索引
print(df_test.mean(axis=1).head()) # axis=1表示按行统计
# 唯一值函数
print('唯一值函数')
print(df['School'].unique()) # unique函数返回唯一值数组
print(df['School'].nunique()) # nunique函数返回唯一值个数
print(df['School'].value_counts()) # value_counts函数返回唯一值计数
df_demo = df[['Gender', 'Transfer', 'Name']]
print(df_demo.drop_duplicates(['Gender', 'Transfer'], keep='last')) # drop_duplicates函数返回多个列的唯一值组合
print(df_demo.drop_duplicates(['Gender', 'Name'], keep=False).head()) # drop_duplicates函数返回多个列的唯一值组合, keep参数表示保留哪个值, False表示全部删除

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='object')
Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer'], dtype='object')
汇总函数
                          School     Grade            Name  Gender  Height  \
0  Shanghai Jiao Tong University  Freshman    Gaopeng Yang  Female   158.9   
1              Peking University  Freshman  Changqiang You    Male   166.5   
2  Shanghai Jiao Tong University    Senior         Mei Sun    Male   188.9   

   Weight Transfer  
0    46.0        N  
1    70.0        N  
2    89.0        N  
                            School      Grade            Name  Gender  Height  \
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua Universi

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('../data/learn_pandas.csv')
# 提取前7列
df = df[df.columns[:7]]
# 替换函数
print('替换函数')
print(df['Gender'].replace({'Female':0, 'Male':1}).head()) # 通过字典替换
print(df['Gender'].replace(['Female', 'Male'], [0, 1]).head()) # 通过列表替换
series = pd.Series([1, 2, 'a', 1, 2, 'b'])
print(series.replace([1, 2], method='bfill')) # method参数表示用后一个最近未被替换的值进行替换
print(series.replace([1, 2], method='ffill')) # method参数表示用前一个最近未被替换的值进行替换
# 逻辑替换
print('逻辑替换')
series = pd.Series([-1, 1.2345, 100, -50])
print(series.where(series<0)) # where函数返回满足条件的值, 不指定值时不满足的值用NaN填充
print(series.where(series<0, 0)) # where函数返回满足条件的值, 指定值时不满足的值用指定值填充
print(series.mask(series<0)) # mask函数返回不满足条件的值, 不指定值时满足的值用NaN填充
print(series.mask(series<0, 0)) # mask函数返回不满足条件的值, 指定值时满足的值用指定值填充
# 数值替换
print('数值替换')
print(series)
print(series.round(2)) # round函数返回指定精度的四舍五入值
print(series.abs()) # abs函数返回绝对值
print(series.clip(0, 2)) # clip函数返回截断值, 小于0的值替换为0, 大于2的值替换为2
# 排序函数
print('排序函数')
df_test = df[['Grade', 'Name', 'Height', 'Weight']].set_index(['Grade', 'Name']) # 把年级和名字当成索引
print(df_test.sort_values('Height').head()) # sort_values函数返回按指定列排序的结果
print(df_test.sort_values('Height', ascending=False).head()) # sort_values函数返回按指定列排序的结果, ascending参数表示升序或降序
# 多列排序
print('多列排序')
print(df_test.sort_values(['Weight', 'Height'], ascending=[True, False]).head()) # sort_values函数返回按指定列排序的结果, ascending参数表示升序或降序
# 索引排序
print('索引排序')
print(df_test.sort_index(level=['Grade', 'Name'], ascending=[True, False]).head()) # sort_index函数返回按指定索引排序的结果, level参数表示索引层级, ascending参数表示升序或降序
# apply方法, 用于DataFrame的行/列的迭代
print('apply方法')
df_demo = df[['Height', 'Weight']]
print(df_demo.apply(lambda x: x.mean())) # apply函数返回对每一列应用函数的结果
print(df_demo.apply(lambda x: x.mean(), axis=1).head()) # apply函数返回对每一行应用函数的结果

替换函数
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64
0    a
1    a
2    a
3    b
4    b
5    b
dtype: object
0    1
1    1
2    a
3    a
4    a
5    b
dtype: object
逻辑替换
0    -1.0
1     NaN
2     NaN
3   -50.0
dtype: float64
0    -1.0
1     0.0
2     0.0
3   -50.0
dtype: float64
0         NaN
1      1.2345
2    100.0000
3         NaN
dtype: float64
0      0.0000
1      1.2345
2    100.0000
3      0.0000
dtype: float64
数值替换
0     -1.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64
0     -1.00
1      1.23
2    100.00
3    -50.00
dtype: float64
0      1.0000
1      1.2345
2    100.0000
3     50.0000
dtype: float64
0    0.0000
1    1.2345
2    2.0000
3    0.0000
dtype: float64
排序函数
                         Height  Weight
Grade     Name                         
Junior    Xiaoli Chu      145.4    34.0
Senior    Gaomei Lv       147.3    34.0
Sophomore Peng Han        147.8    34.0
Senior    Changli Lv    

C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_10104\1982048481.py:11: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  print(series.replace([1, 2], method='bfill')) # method参数表示用后一个最近未被替换的值进行替换
C:\Users\TerenceWang\AppData\Local\Temp\ipykernel_10104\1982048481.py:12: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  print(series.replace([1, 2], method='ffill')) # method参数表示用前一个最近未被替换的值进行替换


#### 窗口对象

In [19]:
import numpy as np
import pandas as pd
# 滑窗对象rolling
print('滑窗对象')
series = pd.Series([1, 2, 6, 16, 30])
roller = series.rolling(window=2) # window参数表示窗口大小
print(roller)
print('聚合函数的使用')
print(roller.mean()) # mean函数返回滑窗平均值
print('均值使用apply实现')
print(roller.apply(lambda x: x.mean())) # apply函数返回滑窗平均值
print(roller.sum()) # sum函数返回滑窗和
print(roller.cov(series)) # cov函数返回滑窗协方差
print(roller.corr(series)) # corr函数返回滑窗相关系数
# 下面三个类滑窗函数的参数n可以为负值, 代表反方向操作
print(series.shift(3)) # 取向前第n个元素
print(series.diff(1)) # 与向前第n个元素的差值
print(series.pct_change(3)) # 与向前第n个元素相比计算增长率

# 扩张窗口
print('扩张窗口')
print(series.expanding(3).sum()) # expanding函数返回扩张窗口的和(窗口逐步扩张)

滑窗对象
Rolling [window=2,center=False,axis=0,method=single]
聚合函数的使用
0     NaN
1     1.5
2     4.0
3    11.0
4    23.0
dtype: float64
均值使用apply实现
0     NaN
1     1.5
2     4.0
3    11.0
4    23.0
dtype: float64
0     NaN
1     3.0
2     8.0
3    22.0
4    46.0
dtype: float64
0     NaN
1     0.5
2     8.0
3    50.0
4    98.0
dtype: float64
0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64
0    NaN
1    NaN
2    NaN
3    1.0
4    2.0
dtype: float64
0     NaN
1     1.0
2     4.0
3    10.0
4    14.0
dtype: float64
0     NaN
1     NaN
2     NaN
3    15.0
4    14.0
dtype: float64
扩张窗口
0     NaN
1     NaN
2     9.0
3    25.0
4    55.0
dtype: float64
