# 预备知识

#### Python基础(一些语法糖)

In [5]:
# 列表推导式(支持多层嵌套)
print([m + ' ' + n for m in ['ustc', 'nico'] for n in ['edu', 'com']]) 
# 带if选择的条件赋值
value = '666' if 2 > 1 else '444'
print(value)

# 匿名函数
print([(lambda x: x * x)(i) for i in range(10)])
# 用map函数实现, 需要调用list()函数转换为列表
print(list(map(lambda x: x * x, range(10))))

# zip函数将可迭代对象打包成元组, 通常用于循环
L1 = [1, 2, 3, 4]
L2 = ['a', 'b', 'c', 'd']
print(list(zip(L1, L2)))
# 解压操作zip(*)
print(list(zip(*zip(L1, L2))))
for (x, y) in zip(L1, L2):
    print(x, y)
# enumerate函数在迭代时绑定遍历序号, 通常用于循环
print('enumerate result:')
for index, value in enumerate(L2):
    print(index, value)
# 对两个列表建立字典映射时, 可以用zip函数
print(dict(zip(L1, L2)))

['ustc edu', 'ustc com', 'nico edu', 'nico com']
666
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]
[(1, 2, 3, 4), ('a', 'b', 'c', 'd')]
1 a
2 b
3 c
4 d
enumerate result:
0 a
1 b
2 c
3 d
{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


#### Numpy基础

In [16]:
# numpy数组构造
import numpy as np
print(np.array([1, 2, 3]))
# 生成等差数列
print(np.arange(0, 10, 2)) # 起始值, 终止值, 步长
print(np.linspace(1, 5, 11)) # 起始值, 终止值, 样本个数
# 特殊矩阵
print('全0矩阵')
print(np.zeros((2, 3))) # 全0矩阵
print('单位矩阵')
print(np.eye(3)) # 3*3单位矩阵
print(np.eye(3, k=1)) # 3*3单位矩阵, 偏移主对角线为1
print('对角矩阵')
print(np.diag([1, 2, 3])) # 对角矩阵
print('全10矩阵')
print(np.full((2, 3), 10)) # 全10矩阵
print('随机矩阵')
print(np.random.rand(2, 3)) # 随机矩阵0-1均匀分布
print(np.random.randn(2, 3)) # 随机矩阵标准正态分布
print(np.random.randint(0, 10, (2, 3))) # 随机矩阵整数均匀分布(2, 3)为维度
print(np.random.choice([10, 20, 30], (3, 3), p=[0.4, 0.2, 0.4]))# 以一定概率进行选择
print(np.random.permutation(['ustc', 'nico', 'edu', 'com'])) # 打散原列表

[1 2 3]
[0 2 4 6 8]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
全0矩阵
[[0. 0. 0.]
 [0. 0. 0.]]
单位矩阵
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
对角矩阵
[[1 0 0]
 [0 2 0]
 [0 0 3]]
全10矩阵
[[10 10 10]
 [10 10 10]]
随机矩阵
[[0.13371985 0.89374354 0.77169338]
 [0.98236722 0.73904041 0.30859929]]
[[-1.89460649 -0.25769103  0.1788687 ]
 [-1.18546341 -1.14782278 -1.84632015]]
[[1 7 3]
 [9 9 1]]
[[30 20 10]
 [20 20 20]
 [30 30 20]]
['edu' 'ustc' 'com' 'nico']


In [38]:
# numpy数组变形、合并等操作
# 转置
print(np.zeros((2,4)).T)
# 合并
print(np.r_[np.zeros((2, 3)), np.ones((2, 3))]) # 按行合并
print(np.c_[np.zeros((2, 3)), np.ones((2, 3))]) # 按列合并
print(np.c_[np.array([1,1]), np.zeros((2, 3))]) # 一维二维数组合并, 按列合并
# 维度变换 
print(np.random.randn(6).reshape((3, 2))) # 2*3变为3*2
print(np.random.randn(2,3).reshape(-1)) # reshape(-1)将多维数组变为一维数组, 允许一个维数空缺
# 数组切片
print(np.arange(9).reshape(3, 3))
print(np.arange(9).reshape(3, 3)[1:3, 1:3]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[1:3, :]) # 二维数组切片
print(np.arange(9).reshape(3, 3)[np.ix_([1,2], [True, False, True])]) # 在对应的维度上使用布尔索引, 此时不能使用slice切片

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[-0.24454107  0.52428338]
 [ 0.7650059  -1.07872579]
 [ 0.13288399 -0.72405317]]
[-0.53593531 -0.87311507  0.19633392 -0.43977484 -0.36122564 -0.8701521 ]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[[3 4 5]
 [6 7 8]]
[[3 5]
 [6 8]]


In [55]:
# 常用函数
# where函数指定满足条件和不满足条件的填充值
print(np.where(np.arange(9).reshape(3, 3) > 0, 1, 0))
# 返回索引函数: nonzero, argmax, argmin
# nonzero返回非零元素的索引
print(np.nonzero(np.arange(9)))
# argmax返回最大值的索引
print(np.argmax(np.arange(9)))
# argmin返回最小值的索引
print(np.argmin(np.arange(9)))
# any函数: 当序列至少有一个True或非零元素时返回True
print(np.any(np.arange(2)))
# all函数: 当序列所有元素都为True或非零元素时返回True
print(np.all(np.arange(2)))
print(np.arange(1, 5))
# cumprod函数: 返回给定序列的累积乘法结果
print(np.cumprod(np.arange(1, 5)))
# cumsum函数: 返回给定序列的累积加法结果
print(np.cumsum(np.arange(1, 5)))
# diff函数: 返回给定序列的累积差值, 返回长度比原序列少1
print(np.diff(np.arange(1, 5)))
# 统计函数: sum, mean, std, var, max, min, median, average, quantile(全局函数, 不能通过array.quantile()调用)
print(np.quantile(np.arange(1, 5), 0.5)) # 返回给定序列的分位数, 这里是中位数
# 忽略有缺失值数组
print(np.array([1, 2, np.nan, 3]))
print(np.nansum(np.array([1, 2, np.nan, 3])))
print('协方差、相关系数的计算')
print(np.cov(np.array([1, 3, 5, 9]), np.array([1, 5, 3, -9]))) # 协方差
print(np.corrcoef(np.array([1, 2, 5]), np.array([2, 5, 6]))) # 相关系数
# 二维NUmpy数组的axis参数: axis=0表示列的统计指标; axis=1表示行的统计指标
print(np.arange(9).reshape(3, 3).sum(axis=0))
print(np.arange(9).reshape(3, 3).sum(axis=1))

[[0 1 1]
 [1 1 1]
 [1 1 1]]
(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)
8
0
True
False
[1 2 3 4]
[ 1  2  6 24]
[ 1  3  6 10]
[1 1 1]
2.5
[ 1.  2. nan  3.]
6.0
协方差、相关系数的计算
[[ 11.66666667 -16.66666667]
 [-16.66666667  38.66666667]]
[[1.         0.84615385]
 [0.84615385 1.        ]]
[ 9 12 15]
[ 3 12 21]


In [74]:
# 广播机制处理不同维度数组之间的操作
# 标量和数组的操作, 标量自动把大小扩充为数组大小
print(3 * np.random.rand(2, 3) + 2)
# 二维数组之间的操作, 其中一个维度实1*m或者n*1, 则自动扩充为m*n
print(np.ones((2, 3)) + np.zeros((1, 3)))
# 一维数组与二维数组的操作, 将一维数组视作1*m的二维数组
print(np.arange(3) + np.ones((3, 3)))
# 向量内积的计算
print(np.arange(3).dot(np.arange(2, 5)))
# 向量范数和矩阵范数
print(np.linalg.norm(np.arange(4).reshape(2, 2), 'fro'))
# 矩阵乘法
print(np.arange(4).reshape(2, 2) @ (np.arange(4).reshape(2, 2)))


[[4.35869895 4.31867726 3.80496064]
 [4.38257599 2.24020113 4.26423098]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
11
3.7416573867739413
[[ 2  3]
 [ 6 11]]
